#!/bin/bash

DIR="/mnt/db/Data/bkp/diary"

if [[ ! -d "$DIR" ]]; then
    mkdir -p "$DIR"
fi

cd "$DIR" || exit 1

if [[ "$(find ./ -type f | wc -l)" -ge 3 ]]; then
    rm "$(find ./ -type f -printf '%T+ %p\n'\
        | sort | head -n 1 | cut -d ' ' -f 2-)"
fi

sudo zip -r "$(date +%Y_%m_%d).zip" /mnt/db/Data/con/**/*
