#!/usr/bin/env bash

DIR="$HOME/.config/bspwm"
STYLE="emo"
RASI="$DIR/themes/$STYLE/rofi/esch.rasi"


options=("Aceitar Task")

#if [[ -n "$2" ]]; then
#    if (( "$2" > "1" )); then
#		options+=("Adiar task em $2 minutos")
#    elif (( "$2" == "1" )); then
#		options+=("Adiar task em $2 minuto")
#	fi
#fi


selected=$(printf '%s\n' "${options[@]}" | rofi -dmenu \
	-mesg "test" \
	-markup-rows \
	-p "$1" \
	-theme "$RASI" \
	-no-click-to-exit &
)

if [[ -z "$selected" ]]; then
	esch "$@"
elif [[ "$selected" == "${options[0]}" ]]; then
    echo "${@:3}" | sh
#elif [[ "$selected" == "${options[1]}" ]]; then
	# printf "export DISPLAY=:0 && $MYBIN/esch \"%s\" 0 %s" "$1" "${@:3}" | sh
fi
