#!/bin/bash
TODAY_PATH=$(date +"notes/%Y-%m-%d")
VAULT_DIR=$(obs print-default | grep -oP '(?<=Default vault path:  ).*')
DAILY_OBS_ROOT=Cerebral\ Line/Time/Diary
FINAL_FILE="$DAILY_OBS_ROOT"/"$TODAY_PATH"

string=$(cat "$VAULT_DIR"/"$DAILY_OBS_ROOT"/note_template.md)
NEW_DAILY_BLOCK="
###### Escrito em $(date +"%H:%M")
"

if [[ ! -f "$VAULT_DIR"/"$FINAL_FILE".md ]]; then
	obs create "$FINAL_FILE" --open -c "$string$NEW_DAILY_BLOCK"
else
	obs create "$FINAL_FILE" --content "$NEW_DAILY_BLOCK" --append --open
fi
